<?php declare(strict_types=1); ?>
<?php require base_path('app/Views/partials/letters-nav.php'); ?>

<div class="d-flex align-items-center gap-3 mb-4">
    <a href="<?= e(url('/letters/templates')); ?>" class="btn btn-outline-secondary btn-sm"><i class="bi bi-arrow-left"></i> Back</a>
    <div>
        <h5 class="mb-0"><?= e((string) $typeLabel); ?> — Template</h5>
        <?php if ($hasCustom): ?>
            <small class="text-success">Custom template active</small>
        <?php else: ?>
            <small class="text-muted">Using default template</small>
        <?php endif; ?>
    </div>
</div>

<div class="row g-4">
    <div class="col-xl-8">
        <div class="card content-card">
            <div class="card-body p-4">
                <form method="post" action="<?= e(url('/letters/templates/' . e((string) $letterType) . '/save')); ?>">
                    <?= csrf_field(); ?>
                    <div class="mb-3">
                        <label class="form-label fw-semibold">Letter Body</label>
                        <div class="form-text mb-2">Use the placeholders on the right to insert dynamic values. HTML tags like &lt;strong&gt;, &lt;p&gt;, &lt;br&gt; are supported.</div>
                        <textarea name="body_content" class="form-control font-monospace" rows="18" required><?= e((string) $body); ?></textarea>
                    </div>
                    <div class="d-flex gap-2">
                        <button type="submit" class="btn btn-primary"><i class="bi bi-check-lg"></i> Save Template</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-xl-4">
        <div class="card content-card mb-3">
            <div class="card-body p-4">
                <h6 class="mb-3">Available Placeholders</h6>
                <p class="text-muted small mb-3">Click any placeholder to copy it, then paste into the body.</p>
                <?php
                $placeholders = [
                    '{{employee_name}}'   => 'Full name',
                    '{{employee_code}}'   => 'Employee code',
                    '{{job_title}}'       => 'Job title',
                    '{{department}}'      => 'Department',
                    '{{company_name}}'    => 'Company name',
                    '{{branch}}'          => 'Branch',
                    '{{joining_date}}'    => 'Date of joining',
                    '{{employment_type}}' => 'Employment type',
                    '{{purpose}}'         => 'Purpose (from request)',
                    '{{salary_amount}}'   => 'Salary amount (formatted)',
                    '{{additional_info}}' => 'Additional info paragraph',
                    '{{ref_number}}'      => 'Reference number',
                    '{{date}}'            => 'Today\'s date',
                    '{{signer_name}}'     => 'Generated by (HR name)',
                ];
                foreach ($placeholders as $tag => $desc): ?>
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <span class="text-muted small"><?= e($desc); ?></span>
                    <code class="placeholder-chip" style="cursor:pointer;user-select:all;" title="Click to copy"><?= e($tag); ?></code>
                </div>
                <?php endforeach; ?>
            </div>
        </div>

        <?php if ($hasCustom): ?>
        <div class="card content-card">
            <div class="card-body p-4">
                <h6 class="mb-2">Reset to Default</h6>
                <p class="text-muted small mb-3">Discard your custom template and restore the system default.</p>
                <form method="post" action="<?= e(url('/letters/templates/' . e((string) $letterType) . '/reset')); ?>" onsubmit="return confirm('Reset to default template?');">
                    <?= csrf_field(); ?>
                    <button type="submit" class="btn btn-outline-danger btn-sm w-100"><i class="bi bi-arrow-counterclockwise"></i> Reset to Default</button>
                </form>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>

<script>
document.querySelectorAll('.placeholder-chip').forEach(function(chip) {
    chip.addEventListener('click', function() {
        navigator.clipboard.writeText(this.textContent).then(function() {
            chip.style.background = '#d1fae5';
            setTimeout(function() { chip.style.background = ''; }, 800);
        });
    });
});
</script>
